/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ehr/scheduling/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available scheduling slots */
        get: operations["listSchedulingSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ehr/scheduling/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book a scheduling slot */
        post: operations["bookSchedulingSlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ehr/scheduling/{appointmentId}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reschedule an appointment */
        post: operations["rescheduleAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ehr/scheduling/{appointmentId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an appointment */
        post: operations["cancelAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpm/patients/{id}/vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get patient vitals for RPM dashboard */
        get: operations["getRpmPatientVitals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpm/patients/{id}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get patient RPM alerts */
        get: operations["getRpmPatientAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpm/patients/{id}/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get RPM thresholds for patient */
        get: operations["getRpmPatientThresholds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SchedulingSlot: {
            id: string;
            providerId: string;
            locationId?: string | null;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            /** @enum {string} */
            status: "available" | "booked" | "held" | "cancelled";
        };
        SchedulingSlotsResponse: {
            slots: components["schemas"]["SchedulingSlot"][];
        };
        BookSchedulingRequest: {
            slotId: string;
            patientId: string;
            reason?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        BookingResponse: {
            id: string;
            /** @enum {string} */
            status: "booked" | "rescheduled";
            slot: components["schemas"]["SchedulingSlot"];
        };
        RescheduleRequest: {
            /** Format: date-time */
            to: string;
        };
        CancelRequest: {
            reason?: string;
        };
        CancelResponse: {
            id: string;
            /** @enum {string} */
            status: "canceled";
        };
        VitalSample: {
            /** Format: date-time */
            timestamp: string;
            value: number;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        VitalSeries: {
            metric: string;
            unit?: string | null;
            values: components["schemas"]["VitalSample"][];
        };
        RpmVitalsResponse: {
            patientId: string;
            days: number;
            vitals: components["schemas"]["VitalSeries"][];
            summary: {
                totalRecords: number;
                metrics: {
                    metric: string;
                    count: number;
                }[];
            };
        };
        AlertRecord: {
            id: string;
            metric: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
            /** @enum {string} */
            status: "open" | "acknowledged" | "resolved";
            message: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            resolvedAt?: string | null;
            context?: {
                [key: string]: unknown;
            } | null;
        };
        RpmAlertsResponse: {
            patientId: string;
            alerts: components["schemas"]["AlertRecord"][];
        };
        ThresholdRecord: {
            metric: string;
            unit?: string | null;
            minValue?: number | null;
            maxValue?: number | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            updatedAt: string;
        };
        RpmThresholdsResponse: {
            patientId: string;
            thresholds: components["schemas"]["ThresholdRecord"][];
        };
        ErrorResponse: {
            error: string;
            code: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSchedulingSlots: {
        parameters: {
            query?: {
                providerId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulingSlotsResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    bookSchedulingSlot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookSchedulingRequest"];
            };
        };
        responses: {
            /** @description Slot booked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
            /** @description Slot already booked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rescheduleAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescheduleRequest"];
            };
        };
        responses: {
            /** @description Appointment rescheduled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    cancelAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            /** @description Appointment canceled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getRpmPatientVitals: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patient vitals summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RpmVitalsResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getRpmPatientAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patient alerts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RpmAlertsResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getRpmPatientThresholds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patient thresholds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RpmThresholdsResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
}
