/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get lab results
         * @description Retrieve lab results for the authenticated user
         */
        get: operations["getLabResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze lab report
         * @description Upload and analyze a lab report file using AI
         */
        post: operations["analyzeLabReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get analysis status
         * @description Get the status and results of a lab analysis
         */
        get: operations["getAnalysisStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload lab file
         * @description Upload a lab report file for processing
         */
        post: operations["uploadLabFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get lab trends
         * @description Get trending data for lab results over time
         */
        get: operations["getLabTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/error": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lab error test endpoint
         * @description Test endpoint that always returns an error
         */
        get: operations["labError"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze-lab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze lab report (legacy endpoint)
         * @description Legacy endpoint for lab analysis - redirects to /analyze
         */
        post: operations["analyzeLabReportLegacy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LabResult: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            userId?: string;
            /** @example Complete Blood Count */
            testName?: string;
            /** @example 4.5 */
            value?: number;
            /** @example 10^6/uL */
            unit?: string;
            /** @example 4.5-5.5 */
            referenceRange?: string;
            /**
             * @example normal
             * @enum {string}
             */
            status?: "normal" | "borderline" | "high" | "low" | "critical";
            /**
             * Format: date-time
             * @example 2025-01-01T12:00:00Z
             */
            testDate?: string;
            /** @example Quest Diagnostics */
            labName?: string;
            /** @example Results within normal limits */
            doctorNotes?: string;
            /**
             * Format: date-time
             * @example 2025-01-01T12:00:00Z
             */
            createdAt?: string;
        };
        LabResultsResponse: {
            results?: components["schemas"]["LabResult"][];
            pagination?: {
                /** @example 1 */
                page?: number;
                /** @example 20 */
                limit?: number;
                /** @example 100 */
                total?: number;
                /** @example 5 */
                totalPages?: number;
            };
        };
        AnalysisRequest: {
            /**
             * Format: binary
             * @description Lab report file (PDF, image, etc.)
             */
            file: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            patientId?: string;
            metadata?: {
                /**
                 * Format: date
                 * @example 2025-01-01
                 */
                testDate?: string;
                /** @example Quest Diagnostics */
                labName?: string;
                /** @example Complete Blood Count */
                testType?: string;
            };
        };
        AnalysisResponse: {
            /** @example a1 */
            analysisId?: string;
            /**
             * @example ok
             * @enum {string}
             */
            status?: "ok" | "pending" | "processing" | "completed" | "failed";
            /** @example Analysis started successfully */
            message?: string;
            /**
             * Format: date-time
             * @example 2025-01-01T12:05:00Z
             */
            estimatedCompletionTime?: string;
        };
        AnalysisStatus: {
            /** @example a1 */
            id?: string;
            /**
             * @example ready
             * @enum {string}
             */
            status?: "pending" | "processing" | "completed" | "failed";
            findings?: components["schemas"]["Finding"][];
            /** @example 100 */
            progress?: number;
            /**
             * Format: date-time
             * @example 2025-01-01T12:00:00Z
             */
            startedAt?: string;
            /**
             * Format: date-time
             * @example 2025-01-01T12:05:00Z
             */
            completedAt?: string;
            /** @example null */
            errorMessage?: string | null;
        };
        Finding: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /** @example Glucose */
            testName?: string;
            /** @example 95 */
            value?: number;
            /** @example mg/dL */
            unit?: string;
            /** @example 70-100 */
            referenceRange?: string;
            /**
             * @example normal
             * @enum {string}
             */
            status?: "normal" | "borderline" | "high" | "low" | "critical";
            /** @example 0.95 */
            confidence?: number;
            /** @example Glucose level is within normal range */
            aiInterpretation?: string;
        };
        UploadResponse: {
            /** @example u1 */
            id?: string;
            /**
             * @example uploaded
             * @enum {string}
             */
            status?: "uploaded" | "processing" | "completed" | "failed";
            /** @example lab_report_2025_01_01.pdf */
            fileName?: string;
            /** @example 1024000 */
            fileSize?: number;
            /**
             * Format: date-time
             * @example 2025-01-01T12:00:00Z
             */
            uploadedAt?: string;
        };
        TrendsData: {
            /** @example Glucose */
            testName?: string;
            /** @example mg/dL */
            unit?: string;
            data?: {
                /**
                 * Format: date
                 * @example 2025-01-01
                 */
                date?: string;
                /** @example 95 */
                value?: number;
                /**
                 * @example normal
                 * @enum {string}
                 */
                status?: "normal" | "borderline" | "high" | "low" | "critical";
            }[];
        };
        TrendsResponse: {
            series?: components["schemas"]["TrendsData"][];
            /** @example 90d */
            timeframe?: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            patientId?: string;
        };
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            /** @example Analysis failed */
            error?: string;
            /** @example chaos */
            message?: string;
            /** @example ANALYSIS_FAILED */
            code?: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLabResults: {
        parameters: {
            query?: {
                /**
                 * @description Filter by test type
                 * @example pgx
                 */
                type?: "pgx" | "cbc" | "chemistry" | "lipid";
                /** @example 1 */
                page?: number;
                /** @example 20 */
                limit?: number;
                /**
                 * @description Test parameter to trigger error scenarios
                 * @example 1
                 */
                chaos?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lab results retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "results": []
                     *     } */
                    "application/json": components["schemas"]["LabResultsResponse"];
                };
            };
            /** @description Unauthorized (chaos mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyzeLabReport: {
        parameters: {
            query?: {
                /**
                 * @description Test parameter to trigger error scenarios
                 * @example 1
                 */
                chaos?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Lab report file
                     */
                    file: string;
                    /**
                     * Format: uuid
                     * @example 550e8400-e29b-41d4-a716-446655440000
                     */
                    patientId?: string;
                    /** @description JSON metadata about the lab report */
                    metadata?: string;
                };
            };
        };
        responses: {
            /** @description Analysis started successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "analysisId": "a1",
                     *       "status": "ok",
                     *       "message": "Analysis started successfully"
                     *     } */
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Invalid file or request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized (chaos mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAnalysisStatus: {
        parameters: {
            query: {
                /**
                 * @description Analysis ID
                 * @example a1
                 */
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis status retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "a1",
                     *       "status": "ready",
                     *       "findings": [],
                     *       "progress": 100
                     *     } */
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
            /** @description Analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadLabFile: {
        parameters: {
            query?: {
                /**
                 * @description Test parameter to trigger error scenarios
                 * @example 1
                 */
                chaos?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Lab report file
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description File uploaded successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "u1",
                     *       "status": "uploaded",
                     *       "fileName": "lab_report.pdf"
                     *     } */
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Invalid file */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized (chaos mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLabTrends: {
        parameters: {
            query?: {
                /**
                 * @description Number of days to include in trends
                 * @example 30
                 */
                days?: 7 | 30 | 90 | 365;
                /**
                 * @description Specific test names to include
                 * @example [
                 *       "Glucose",
                 *       "Cholesterol"
                 *     ]
                 */
                testNames?: string[];
                /**
                 * @description Test parameter to trigger error scenarios
                 * @example 1
                 */
                chaos?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lab trends retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "series": [],
                     *       "timeframe": "30d"
                     *     } */
                    "application/json": components["schemas"]["TrendsResponse"];
                };
            };
            /** @description Unauthorized (chaos mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    labError: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lab error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "Lab error"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyzeLabReportLegacy: {
        parameters: {
            query?: {
                /**
                 * @description Test parameter to trigger error scenarios
                 * @example 1
                 */
                chaos?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Lab report file
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Analysis started successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "analysisId": "a1",
                     *       "status": "ok"
                     *     } */
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Unauthorized (chaos mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
