/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all medications
         * @description Retrieve all medications for the authenticated user
         */
        get: operations["getMedications"];
        put?: never;
        /**
         * Add a new medication
         * @description Add a new medication to the user's medication list
         */
        post: operations["createMedication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a medication
         * @description Update an existing medication
         */
        put: operations["updateMedication"];
        post?: never;
        /**
         * Delete a medication
         * @description Delete a medication from the user's medication list
         */
        delete: operations["deleteMedication"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search medications
         * @description Search for medications in the database
         */
        get: operations["searchMedications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check drug interactions
         * @description Check for interactions between medications
         */
        get: operations["checkDrugInteractions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get medication reminders
         * @description Get scheduled medication reminders for the user
         */
        get: operations["getMedicationReminders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/error": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Medication error test endpoint
         * @description Test endpoint that always returns an error
         */
        get: operations["medicationError"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Medication: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            userId?: string;
            /** @example Lisinopril */
            name?: string;
            /** @example lisinopril */
            genericName?: string;
            /** @example Prinivil */
            brandName?: string;
            /** @example 10mg */
            dosage?: string;
            /** @example Once daily */
            frequency?: string;
            /**
             * @example oral
             * @enum {string}
             */
            route?: "oral" | "topical" | "injection" | "inhalation" | "sublingual";
            /**
             * Format: date
             * @example 2025-01-01
             */
            startDate?: string;
            /**
             * Format: date
             * @example null
             */
            endDate?: string | null;
            /** @example Dr. John Smith */
            prescribedBy?: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            prescribedById?: string;
            /** @example Take with food */
            instructions?: string;
            /** @example [
             *       "dizziness",
             *       "dry cough"
             *     ] */
            sideEffects?: string[];
            /** @example true */
            isActive?: boolean;
            /**
             * Format: date-time
             * @example 2025-01-01T12:00:00Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @example 2025-01-01T12:00:00Z
             */
            updatedAt?: string;
        };
        MedicationListResponse: {
            items?: components["schemas"]["Medication"][];
            pagination?: {
                /** @example 1 */
                page?: number;
                /** @example 20 */
                limit?: number;
                /** @example 100 */
                total?: number;
                /** @example 5 */
                totalPages?: number;
            };
        };
        CreateMedicationRequest: {
            /** @example Lisinopril */
            name: string;
            /** @example lisinopril */
            genericName?: string;
            /** @example Prinivil */
            brandName?: string;
            /** @example 10mg */
            dosage: string;
            /** @example Once daily */
            frequency: string;
            /**
             * @example oral
             * @enum {string}
             */
            route?: "oral" | "topical" | "injection" | "inhalation" | "sublingual";
            /**
             * Format: date
             * @example 2025-01-01
             */
            startDate: string;
            /**
             * Format: date
             * @example null
             */
            endDate?: string | null;
            /** @example Dr. John Smith */
            prescribedBy?: string;
            /** @example Take with food */
            instructions?: string;
        };
        CreateMedicationResponse: {
            /**
             * Format: uuid
             * @example m1
             */
            id?: string;
            /** @example created */
            status?: string;
            /** @example Medication added successfully */
            message?: string;
        };
        UpdateMedicationRequest: {
            /** @example Lisinopril */
            name?: string;
            /** @example 10mg */
            dosage?: string;
            /** @example Once daily */
            frequency?: string;
            /** @example Take with food */
            instructions?: string;
            /** @example true */
            isActive?: boolean;
        };
        UpdateMedicationResponse: {
            /** @example m1 */
            id?: string;
            /** @example updated */
            status?: string;
            /** @example Medication updated successfully */
            message?: string;
        };
        DeleteMedicationResponse: {
            /** @example m1 */
            id?: string;
            /** @example deleted */
            status?: string;
            /** @example Medication deleted successfully */
            message?: string;
        };
        MedicationSearchResult: {
            /** @example lipitor */
            id?: string;
            /** @example Lipitor */
            name?: string;
            /** @example atorvastatin */
            generic?: string;
            /** @example [
             *       "Lipitor",
             *       "Atorvastatin"
             *     ] */
            brandNames?: string[];
            /** @example [
             *       "10mg tablet",
             *       "20mg tablet",
             *       "40mg tablet"
             *     ] */
            dosageForms?: string[];
            /** @example Statin */
            category?: string;
            /** @example Used to lower cholesterol levels */
            description?: string;
        };
        MedicationSearchResponse: {
            items?: components["schemas"]["MedicationSearchResult"][];
            /** @example lipitor */
            q?: string;
            /** @example 1 */
            count?: number;
        };
        DrugInteraction: {
            /** @example [
             *       "lipitor",
             *       "warfarin"
             *     ] */
            pair?: string[];
            /**
             * @example major
             * @enum {string}
             */
            severity?: "minor" | "moderate" | "major" | "severe";
            /** @example Monitor INR closely */
            note?: string;
            /** @example Atorvastatin may increase the anticoagulant effect of warfarin */
            description?: string;
            /** @example Monitor INR more frequently when starting, stopping, or changing atorvastatin dose */
            management?: string;
        };
        InteractionsResponse: {
            interactions?: components["schemas"]["DrugInteraction"][];
            /** @example 2 */
            drugCount?: number;
            /** @example [
             *       "lipitor",
             *       "warfarin"
             *     ] */
            checked?: string[];
        };
        MedicationReminder: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            medicationId?: string;
            /** @example Lisinopril */
            medicationName?: string;
            /** @example 10mg */
            dosage?: string;
            /**
             * Format: time
             * @example 08:00
             */
            scheduledTime?: string;
            /** @example daily */
            frequency?: string;
            /** @example true */
            isActive?: boolean;
            /**
             * Format: date-time
             * @example 2025-01-01T08:00:00Z
             */
            lastTaken?: string | null;
            /**
             * Format: date-time
             * @example 2025-01-02T08:00:00Z
             */
            nextDue?: string;
        };
        RemindersResponse: {
            reminders?: components["schemas"]["MedicationReminder"][];
        };
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            /** @example Medication not found */
            error?: string;
            /** @example chaos */
            message?: string;
            /** @example MEDICATION_NOT_FOUND */
            code?: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMedications: {
        parameters: {
            query?: {
                /** @example 1 */
                page?: number;
                /** @example 20 */
                limit?: number;
                /**
                 * @description Filter by active status
                 * @example true
                 */
                active?: boolean;
                /**
                 * @description Test parameter to trigger error scenarios
                 * @example 1
                 */
                chaos?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Medications retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "items": []
                     *     } */
                    "application/json": components["schemas"]["MedicationListResponse"];
                };
            };
            /** @description Unauthorized (chaos mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createMedication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMedicationRequest"];
            };
        };
        responses: {
            /** @description Medication created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "m1",
                     *       "status": "created"
                     *     } */
                    "application/json": components["schemas"]["CreateMedicationResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMedication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example m1 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMedicationRequest"];
            };
        };
        responses: {
            /** @description Medication updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "m1",
                     *       "status": "updated"
                     *     } */
                    "application/json": components["schemas"]["UpdateMedicationResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Medication not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteMedication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example m1 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Medication deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "m1",
                     *       "status": "deleted"
                     *     } */
                    "application/json": components["schemas"]["DeleteMedicationResponse"];
                };
            };
            /** @description Medication not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchMedications: {
        parameters: {
            query: {
                /**
                 * @description Search query
                 * @example lipitor
                 */
                q: string;
                /** @example 20 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "items": [
                     *         {
                     *           "id": "lipitor",
                     *           "name": "Lipitor",
                     *           "generic": "atorvastatin"
                     *         }
                     *       ],
                     *       "q": "lipitor",
                     *       "count": 1
                     *     } */
                    "application/json": components["schemas"]["MedicationSearchResponse"];
                };
            };
            /** @description Invalid search query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    checkDrugInteractions: {
        parameters: {
            query?: {
                /**
                 * @description First medication to check
                 * @example lipitor
                 */
                drugA?: string;
                /**
                 * @description Second medication to check
                 * @example warfarin
                 */
                drugB?: string;
                /**
                 * @description List of medication IDs to check for interactions
                 * @example [
                 *       "med1",
                 *       "med2",
                 *       "med3"
                 *     ]
                 */
                ids?: string[];
                /**
                 * @description Test parameter to trigger error scenarios
                 * @example 1
                 */
                chaos?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Drug interactions retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "interactions": [
                     *         {
                     *           "pair": [
                     *             "lipitor",
                     *             "warfarin"
                     *           ],
                     *           "severity": "major",
                     *           "note": "Monitor INR closely"
                     *         }
                     *       ]
                     *     } */
                    "application/json": components["schemas"]["InteractionsResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized (chaos mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "chaos"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMedicationReminders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Medication reminders retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "reminders": []
                     *     } */
                    "application/json": components["schemas"]["RemindersResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    medicationError: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Medication error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "Medication error"
                     *     } */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
